name: coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install libs
      run: sudo apt-get install -y libegl1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-devel.txt
    - name: Run coverage
      run: python -m coverage run -m pytest tests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Publish code coverage badge
      run: |
        set -x
        total=`python3 -c "import sys, json; print(json.load(sys.stdin)['totals']['percent_covered_display'])" < coverage.json`
        if (( $(echo "$total <= 40" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$total > 70" | bc -l) )); then
          COLOR=green
        else
          COLOR=orange
        fi
        curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > badge.svg
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code coverage badge
        path: badge.svg
